Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -69,6 +69,13 @@ export NUGET_PACKAGES="${CACHE_DIR}/nuget/cache"
 info "publish ${PROJECT_FILE} for ${BUILD_CONFIGURATION} on ${OUTPUT_DIR}"
 dotnet publish $PROJECT_FILE --output ${BUILD_DIR}/${OUTPUT_DIR} --configuration ${BUILD_CONFIGURATION} --self-contained --runtime linux-x64
 
+### Copy Aptfile from API folder to root
+if [ -f "$BUILD_DIR/src/Ortho2Signature.API/Aptfile" ]; then
+    cp "$BUILD_DIR/src/Ortho2Signature.API/Aptfile" "$BUILD_DIR/"
+else
+    echo "Aptfile not found in API directory"
+    exit 1
+fi
 rm -rf ${BUILD_DIR}/src
 
 # List the contents of the output directory again after cleanup
