Update compile(prueba)

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,8 +8,8 @@ set -o nounset    # fail on unset variables
 unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
 
 if [ "$STACK" == "cedar-14" ]; then
-	echo "cedar-14 isn't supported"
-	exit 1
+    echo "cedar-14 isn't supported"
+    exit 1
 fi
 
 ### Configure directories
@@ -21,6 +21,14 @@ OUTPUT_DIR=${OUTPUT_DIR:-heroku_output}
 
 mkdir -p $BUILD_DIR/.profile.d
 cp $BP_DIR/profile/* $BUILD_DIR/.profile.d/
+
+### Copy Aptfile from API folder to root
+if [ -f "$BUILD_DIR/API/Aptfile" ]; then
+    cp "$BUILD_DIR/API/Aptfile" "$BUILD_DIR/"
+else
+    echo "Aptfile not found in API directory"
+    exit 1
+fi
 
 ### Load dependencies
 source $BP_DIR/lib/utils
@@ -39,46 +47,47 @@ install_dotnet $BUILD_DIR $CACHE_DIR $DOTNET_SDK_VERSION $DOTNET_RUNTIME_VERSION
 
 export PATH="${BUILD_DIR}/.heroku/dotnet:${PATH}"
 
-info "Installing IronPdf.Linux package"
-dotnet add package IronPdf.Linux
-
 cd $BUILD_DIR
 
 if [ -f ${BUILD_DIR}/dotnet-tools.json ] || [ -f ${BUILD_DIR}/.config/dotnet-tools.json ]; then
-	dotnet tool restore
+    dotnet tool restore
 fi
 
 if [ -z ${PROJECT_FILE:-} ]; then
-	PROJECT_FILE=$(x=$(dirname $(find ${BUILD_DIR} -maxdepth 5 -iname Startup.cs -o -iname Program.cs -o -iname Program.fs | head -1)); while [[ "$x" =~ $BUILD_DIR ]] ; do find "$x" -maxdepth 1 -name *.fsproj -o -name *.csproj; x=`dirname "$x"`; done)
+    PROJECT_FILE=$(x=$(dirname $(find ${BUILD_DIR} -maxdepth 5 -iname Startup.cs -o -iname Program.cs -o -iname Program.fs | head -1)); while [[ "$x" =~ $BUILD_DIR ]] ; do find "$x" -maxdepth 1 -name *.fsproj -o -name *.csproj; x=`dirname "$x"`; done)
+fi
+
+if [ -z ${PROJECT_FILE:-} ]; then
+    echo "No project file found."
+    exit 1
 fi
 
 topic "Project File"
 info $PROJECT_FILE
 
 if [ -z ${PROJECT_NAME:-} ]; then
-	PROJECT_NAME=$(basename ${PROJECT_FILE%.*})
+    PROJECT_NAME=$(basename ${PROJECT_FILE%.*})
 fi
 
 topic "Project Name"
 info $PROJECT_NAME
 
+cd $(dirname $PROJECT_FILE)
+
+### Install IronPdf.Linux package
+info "Installing IronPdf.Linux package"
+dotnet add package IronPdf.Linux
+
 if [ -n "$(cat $PROJECT_FILE | grep 'netcoreapp2.0')" ]; then
-	topic "WARNING"
-	info "For netcoreapp2.0 use https://github.com/jincod/dotnetcore-buildpack#v2.1.200" | indent
-	info "More info https://github.com/jincod/dotnetcore-buildpack/issues/44" | indent
+    topic "WARNING"
+    info "For netcoreapp2.0 use https://github.com/jincod/dotnetcore-buildpack#v2.1.200" | indent
+    info "More info https://github.com/jincod/dotnetcore-buildpack/issues/44" | indent
 fi
 export NUGET_PACKAGES="${CACHE_DIR}/nuget/cache"
 
 info "publish ${PROJECT_FILE} for ${BUILD_CONFIGURATION} on ${OUTPUT_DIR}"
 dotnet publish $PROJECT_FILE --output ${BUILD_DIR}/${OUTPUT_DIR} --configuration ${BUILD_CONFIGURATION} --self-contained --runtime linux-x64
 
-### Copy Aptfile from API folder to root
-if [ -f "$BUILD_DIR/src/Ortho2Signature.API/Aptfile" ]; then
-    cp "$BUILD_DIR/src/Ortho2Signature.API/Aptfile" "$BUILD_DIR/"
-else
-    echo "Aptfile not found in API directory"
-    exit 1
-fi
 rm -rf ${BUILD_DIR}/src
 
 # List the contents of the output directory again after cleanup
@@ -88,19 +97,17 @@ du -sh ${BUILD_DIR}/* | awk '{printf "%-10s %-s\n", $1, $2}'
 info "Listing contents of ${BUILD_DIR} after cleanup with sizes in MB"
 du -sh ${BUILD_DIR}/${OUTPUT_DIR}/* | awk '{printf "%-10s %-s\n", $1, $2}'
 
-
-
 if [ -f ${BUILD_DIR}/Procfile ]; then
-	topic "WARNING"
-	echo "Be careful with custom Procfile" | indent
+    topic "WARNING"
+    echo "Be careful with custom Procfile" | indent
 else
-	echo "Add web process to Procfile" | indent
-	cat << EOT >> ${BUILD_DIR}/Procfile
+    echo "Add web process to Procfile" | indent
+    cat << EOT >> ${BUILD_DIR}/Procfile
 web: cd \$HOME/heroku_output && ./${PROJECT_NAME}
 EOT
 fi
 
 if [ -n ${HEROKUISH:-""} ]; then
-	echo "Override Procfile for herokuish" | indent
-	echo "web: \$HOME/heroku_output/${PROJECT_NAME}" > ${BUILD_DIR}/Procfile
+    echo "Override Procfile for herokuish" | indent
+    echo "web: \$HOME/heroku_output/${PROJECT_NAME}" > ${BUILD_DIR}/Procfile
 fi
